name: Build

on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  win-x64-fd:
    name: Windows Build (Framework Dependent)
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish
        run: dotnet publish Whiskers -c Release -r win-x64 -p:PublishSingleFile=true --no-self-contained

      - name: Create release folder
        run: |
          $FolderName = 'dist'
          New-Item $FolderName -ItemType Directory
          Copy-Item Whiskers\bin\Release\net8.0-windows\win-x64\publish\*.* $FolderName
          Compress-Archive -Path $FolderName -DestinationPath Whiskers-win-x64-fd.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: Whiskers-win-x64-fd
          path: Whiskers-win-x64-fd.zip

  win-x64-sc:
    name: Windows Build (Self-Contained)
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish
        run: dotnet publish Whiskers -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true

      - name: Create release folder
        run: |
          $FolderName = 'dist'
          New-Item $FolderName -ItemType Directory
          Copy-Item Whiskers\bin\Release\net8.0-windows\win-x64\publish\*.* $FolderName
          Compress-Archive -Path $FolderName -DestinationPath Whiskers-win-x64-sc.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: Whiskers-win-x64-sc
          path: Whiskers-win-x64-sc.zip

  update_releases_page:
    name: Upload builds to Releases
    if: github.event_name != 'pull_request'
    needs:
      - win-x64-fd
      - win-x64-sc
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Set up variables
        id: vars
        run: |
          echo "date_now=$(date --rfc-3339=seconds)" >> "${GITHUB_OUTPUT}"

      - name: Download build artifacts from previous jobs
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Upload builds to Releases
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: artifacts/*/*
          body: |
            **This release is automatically created whenever any changes are made to the project. This release may contain bugs and other oddities.**

            **Use at your own discretion!**

            - Last build date: `${{steps.vars.outputs.date_now}}`
            - Reference commit: ${{github.sha}}
            - Commit message: `${{github.event.head_commit.message}}` by @${{github.event.head_commit.author.name}}
          name: Development build
          prerelease: true
          removeArtifacts: true
          tag: dev-build
